---
- name: Get Go Testsum release info
  become: false
  uri:
    url: https://api.github.com/repos/gotestyourself/gotestsum/releases/latest
    headers:
      Accept: 'application/vnd.github.v3+json'
    return_content: yes
  register: gotestsum_release_info
  changed_when: false

- name: Get Available Go Testsum Version
  become: false
  set_fact:
    gotestsum_version: "{{ gotestsum_release_info.json.tag_name | regex_search('\\d+\\.\\d+\\.\\d+') }}"
  changed_when: false

- name: Set Go Testsum Download URL
  become: false
  vars:
    linux_tarball_query: "assets[?name=='gotestsum_{{ gotestsum_version }}_linux_amd64.tar.gz'].browser_download_url"
  set_fact:
    gotestsum_download_url: "{{ gotestsum_release_info.json | json_query(linux_tarball_query) | first }}"
  changed_when: false

